### ISSUE TITLE
Versions required for dependencies not made clear

### ISSUE THREAD

**Issue by thePalindrome** [GWYOG/GTNEIOrePlugin#3]
I found that to build this, I needed:
gregtech-5.09.30-dev.jar (5.09.31 failed to compile)
gregtech_1.7.10-6.05.22-dev.jar (this was the latest official dev build)

Adding this to the readme would be much appreciated

**Comment by GWYOG** [comment]
Have improved the readme. :)
I used the older versions of GT5 & GT6 to build since this repository hasn't been updated for many months, and I haven't tried to use 5.09.31 to build either. So I don't know why 5.09.31 fails to compile.
If this mod needs update to be compatible with the new versions of GT, issues and prs are always welcome. :D
